### ISSUE TITLE
Bug in Mxalloc() detection

### ISSUE THREAD

**Issue by mikrosk** [pmandin/cleancode#2]
https://github.com/pmandin/cleancode/blob/9dd4e6fb05cf2ab880103b6d0902a88b5d267ceb/common/mxalloc.c#L33 contains quite a suspicious code:

- it checks for major GEMDOS version 1.x (is there such?)
- it uses `|` instead of `||` for the check but it works by chance because previous condition always (?) fails

**Comment by pmandin** [comment]
I don't know where the check for the lower byte comes from, maybe difference between MegaSTe and TT (both have 0.19) ?
I copy/pasted it from SDL, (so same problem there).

Anyway, fixed
